### ISSUE TITLE
Request for proper attribution

### ISSUE THREAD

**Issue by Sven-Bo** [VishalTyagi098/Python_Excel_Interactive_Dashboard#1]
I noticed you used content from my YouTube video [https://youtu.be/Sb0A9i6d320](https://youtu.be/Sb0A9i6d320) this article without giving me proper credit. While it is not illegal to use someone else's work as inspiration, it is not ethical to present it as your own original work. I request that you properly cite the original source and give credit where it is due. This is good practice and shows respect for the hard work and effort I have put into creating the content.

**Comment by VishalTyagi098** [comment]
Apologies for the inconvenience; as this is my first blog, I'm still learning a lot. I appreciate you pointing out my error; I've given correct credit to your original work.
